(in-package :liwm)

(defun main (&key display)
  (start-window-manager
   (make-window-manager display)
   :initialized-hook (lambda ()
                       (bind-key (make-key-input "t" :meta t :control t)
                                 (get-command "xterm"))
                       (bind-key (make-key-input "n" :super t)
                                 (get-command "next window"))
                       (bind-key (make-key-input "p" :super t)
                                 (get-command "previous window"))
                       (bind-key (make-key-input "F4" :meta t)
                                 (get-command "quit window"))
                       (bind-key (make-key-input "x" :super t)
                                 (get-command "maximize window"))

                       (bind-key (make-key-input "1" :super t)
                                 (get-command "change desktop 1"))
                       (bind-key (make-key-input "2" :super t)
                                 (get-command "change desktop 2"))
                       (bind-key (make-key-input "3" :super t)
                                 (get-command "change desktop 3"))
                       (bind-key (make-key-input "4" :super t)
                                 (get-command "change desktop 4"))

                       (bind-key (make-key-input "1" :super t :control t)
                                 (get-command "move window to desktop 1"))
                       (bind-key (make-key-input "2" :super t :control t)
                                 (get-command "move window to desktop 2"))
                       (bind-key (make-key-input "3" :super t :control t)
                                 (get-command "move window to desktop 3"))
                       (bind-key (make-key-input "4" :super t :control t)
                                 (get-command "move window to desktop 4")))))
